version: "3.8"

services:
  sql_server:
    container_name: sql_server
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Mssql!Passw0rd
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql
